sudo: required

services:
  - docker

before_install:
  - docker build -t hongaponga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hongaponga/react-test npm test

after_success:
  - docker build -t liewshanhong/multi-client ./client
  - docker build -t liewshanhong/multi-nginx ./nginx
  - docker build -t liewshanhong/multi-server ./server
  - docker build -t liewshanhong/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push liewshanhong/multi-client
  - docker push liewshanhong/multi-nginx 
  - docker push liewshanhong/multi-server
  - docker push liewshanhong/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ca-central-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-ca-central-1-559022758883'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
